server/.gitignore
server/controllers/UserController.js
server/controllers/test.js
server/index.js
server/models/ReferralRequest.js
server/models/ReferralSlot.js
server/models/RequestBatch.js
server/models/User.js
server/routes/UserRouter.js
server/routes/test.js

Commit to set up database schema

Set up database schema

---

server/models/Opening.js
server/models/OpeningBatch.js
server/models/Request.js
server/models/RequestBatch.js

Commit to change "slot" to "opening" in database schema

Change slot to opening in schema

---

server/controllers/RequestBatchController.js
server/index.js
server/models/RequestBatch.js
server/routes/RequestBatchRouter.js

Commit to implement CREATE api endpoint for creating a RequestBatch

Implement CREATE endpoint for RequestBatch

---

server/index.js
server/models/Opening.js
server/models/OpeningBatch.js
server/models/Request.js
server/models/RequestBatch.js

Commit to fix initial errors such as not using ES6 export and singular noun in api route

Fix initial errors

---

client/src/App.jsx
client/src/components/Sidebar.jsx
client/src/components/SidebarItem.jsx
client/src/components/icons/HomePageIcon.jsx
client/src/components/icons/LogoutPageIcon.jsx
client/src/components/icons/OpeningPageIcon.jsx
client/src/components/icons/ProfilePageIcon.jsx
client/src/components/icons/RequestPageIcon.jsx
client/src/pages/RequestBatchSelectionPage/RequestBatchSelectionForm.jsx
client/src/pages/RequestBatchSelectionPage/index.jsx

Commit to finish UI for sidebar

Finish UI for sidebar

---

server/controllers/AuthController.js
server/index.js
server/package-lock.json
server/package.json
server/routes/AuthRouter.js

frontend: 
- basic UI for login
- Get Authorization code from LinkedIn
Backend:
- Route for get user info by LinkedIn authorization code

Auth w linkedin

---

client/src/App.jsx
client/src/pages/LandingPage/Redirect.jsx
client/src/pages/OnboardPage/ExperienceForm.jsx
client/src/pages/ProfilePage/ProfilePage.jsx
client/src/state/index.js

The codes take user info data returned from backend to navigate user to either ProfilePage or OnboardPage
- client/src/pages/LandingPage/Redirect.jsx: Handle storing data into redux store using changeUser reducer and direct user to appropriate page
- client/src/state/index.js: add changeUser reducer
https://github.com/hoangr1010/Cupid/assets/137933787/9f922424-c7db-4a09-a412-9b139d1b4d05

Direct user to proper page after logging in

---

server/controllers/RequestController.js
server/index.js
server/routes/RequestRouter.js

- This code allows users to make POST request to localhost:PORT/request/create in order to create a new request.
- server/controllers/RequestController.js
- server/routes/RequestRouter.js
- server/index.js
Server runs ok
___
___

Implement CREATE + GET api for request

---

client/src/App.jsx
client/src/components/Sidebar.jsx
client/src/components/SidebarItem.jsx
client/src/index.css
client/src/pages/OpeningDashboardPage/OpeningDashboardPage.jsx
client/tailwind.config.js

- Add a functional sidebar with simple style
- Create styling template for button
https://github.com/hoangr1010/Cupid/assets/137933787/a58d47ef-7b1e-4df8-ac0d-f0238eabcba7

Add sidebar with simple style

---

server/controllers/RequestController.js
server/controllers/date-utilities.js
server/models/Request.js
server/routes/RequestRouter.js

- Add GET api endpoint for getting all requests created within 3 months.
- Added created_date field to Request's schema.
- server/controllers/RequestController.js
- server/routers/RequestRouter.js
- server/models/Request.js

Implement GET api for all requests within 3 months

---

server/models/User.js

Add field resume_url to UserSchema
- server/models/User.js
The change does not break anything :))

add field resume_url to UserSchema

---

client/src/index.js

- Set up redux persist, redux data is sync with local storage
- index.js: set up redux persist
https://github.com/hoangr1010/Cupid/assets/117782458/4f415728-d6a7-46c5-be25-e6b8b7d216e3

set up redux persist

---

client/package-lock.json
client/package.json
client/src/index.js

- install and implement toast package named Sonner https://sonner.emilkowal.ski/
- client/src/index.js: added Toaster component that need to be in root component, and can serve in all component
This is only for test, the app doesn't have this implementation
https://github.com/hoangr1010/Cupid/assets/117782458/3b577700-b7f4-4859-849f-0482310fd5ed

install & implement sonner

---

client/src/components/Sidebar/BottomBar.jsx
client/src/components/Sidebar/SidebarItem.jsx
client/src/components/Sidebar/index.jsx
client/src/state/index.js
client/src/utils/auth.js
server/controllers/AuthController.js

- We can see avatar in bottom bar and logout
- client/src/components/Sidebar/BottomBar.jsx: Bottombar UI and functionality
- client/src/components/Sidebar/index.jsx: make it more responsive
- client/src/state/index.js: add clearAuth reducer to clear data of this slice
- client/src/utils/auth.js: create function logout to clear data in redux and localStorage, then redirect to landingpage
- server/controllers/AuthController.js: add picture URL when send user data to frontend
- Any prove for testing? (image/video to prove)
https://github.com/hoangr1010/Cupid/assets/117782458/30246cf9-b47b-4ac1-a1d2-adab1fa7dc51

add bottombar in sidebar

---

.github/workflows/main.yml
package-lock.json

This PR is to merge to test yml file

add yml file

---

.github/workflows/main.yml

- Github actions will automatically run test whenever PR is created
- .github/workflows/main.yml
- Any prove for testing? (image/video to prove)

update yml file

---

client/src/api/auth.js
client/src/components/Sidebar/BottomBar.jsx
client/src/state/index.js
server/controllers/Auth.js
server/models/User.js

- resolve #67 
- In order to make updateUser reducer in auth slice, I save pictureUrl in User model
- client/src/api/auth.js
- client/src/components/Sidebar/BottomBar.jsx
- client/src/state/index.js: change name "changeUser" -> "updateUser", and save the whole payload to user object
- server/controllers/Auth.js: save pictureUrl to User object and send only User object to frontend
- server/models/User.js: add picture_url model
things work fine
https://github.com/hoangr1010/Cupid/assets/117782458/ff9b3387-4f97-48fb-80fd-ebc35627113b

change User model, update picture_url functionality

---

server/controllers/Request.js

- Implement data validation:
- An user can have at most 10 requests at any time.
- An user cannot have two requests with the same priority.
- /server/controllers/Request.js

Request limit

---

client/src/App.jsx
client/src/api/user.js
client/src/pages/OnboardPage/ResumeSubmit.jsx
server/controllers/User.js
server/routes/User.js

- Connect frontend with backend to store user's resume link into database
- Update the redux store with new user's data, which includes the user's resume link
- client/src/App.jsx: attached userid to the headers every time sending request to backend
- client/src/api/user.js: api request to backend
- client/src/pages/OnboardPage/ResumeSubmit.jsx: Submit button call updateResume function to make API request and navigate to profile page
- server/controllers/User.js: Update resume link in database
- server/routes/User.js: router
https://github.com/hoangr1010/Cupid/assets/137933787/5d1c4ebd-cabc-44fa-9b2d-db0a4d01c2a4

Update resume link

---

client/src/App.jsx
client/src/pages/RequestDashboardPage/RequestDashboard.jsx

- Add a button to navigate from RequestDashboard to CreateRequestPage.
- client/src/App.jsx
- client/src/pages/RequestDashboardPage/RequestDashboard.jsx
https://github.com/hoangr1010/Cupid/assets/140891599/400f56ab-5b00-483b-ba28-762e82f232f1

Add button to navigate to CreateRequest page

---

client/src/api/opening.js
client/src/index.js
client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx
client/src/pages/OpeningDashboardPage/GetAllOpenings.jsx
client/src/state/index.js

- Implemented Redux in GetAllOpenings and CreateOpeningSlots
- client/src/api/opening.js
- client/src/index.js
- client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx
- client/src/pages/OpeningDashboardPage/GetAllOpenings.jsx
- client/src/state/index.js
https://github.com/hoangr1010/Cupid/assets/93673250/2337e52e-66f9-4d14-b989-82aff2379956

Added Redux for GetAllOpenings and CreateOpeningSlots

---

client/src/pages/LandingPage/Redirect.jsx

- fix bugs #88 
- client/src/pages/LandingPage/Redirect.jsx: delete dependecies of useEffect for avoiding rerender
Uploading Screen Recording 2024-04-29 at 2.28.00 PM.mov…

fix bug onboard navigation

---

client/src/api/user.js
server/controllers/Opening.js
server/controllers/Request.js
server/controllers/User.js
server/middleware/Request.js
server/middleware/User.js
server/models/Request.js
server/routes/Opening.js
server/routes/Request.js
server/routes/User.js
server/test/Opening/createOpening.js
server/test/Opening/getAllOpening.js
server/test/Opening/getOneOpening.js
server/test/Opening/index.js
server/test/Request/createRequest.js
server/test/Request/getAllRequest.js
server/test/Request/getAllRequests.js
server/test/Request/getOneRequest.js
server/test/Request/index.js
server/test/User/index.js
server/test/User/updateResume.js
server/test/index.test.js

- I add full test case for all endpoint in server at the moment
- server/controllers/Opening.js: modify logic to pass the test
- server/controllers/Request.js: modify logic to pass the test
- server/middleware/User.js: add checkUserId middleware that can check if userid in header and if userid exist in db
- server/routes/Opening.js: modify route and add checkUserId middleware
- server/routes/Request.js: modify route and add checkUserId middleware
- server/routes/User.js: add checkUserId middleware
- server/test/Opening: add test for opening
- server/test/Request: add test for Request
- server/test/User/updateResume.js: add test for updateResume endpoint

Unit test server

---

matching-algorithm/.gitignore
matching-algorithm/models/Opening.js
matching-algorithm/models/Request.js
matching-algorithm/models/User.js
matching-algorithm/package-lock.json
matching-algorithm/package.json
matching-algorithm/script/index.js
matching-algorithm/utils/connectDB.js
matching-algorithm/utils/date.js
server/seeds/sampleData.js

- Make a script that runs first-come-first-serve matching algorithm based on the "scale" field in Request Schema.
- To run matching algorithm, run the following command:
```
npm run algo
```
- matching-algorithm/.gitignore
- matching-algorithm/models/Opening.js
- matching-algorithm/models/Request.js
- matching-algorithm/models/User.js
- matching-algorithm/package-lock.json
- matching-algorithm/package.json
- matching-algorithm/script/index.js
- matching-algorithm/utils/connectDB.js
- matching-algorithm/utils/date.js
https://github.com/hoangr1010/Cupid/assets/140891599/d4dd1abe-b8af-490f-8a92-08b292e97a3f

Matching algorithm (first-come-first-serve) based on scale

---

client/src/pages/OnboardPage/ResumeSubmit.jsx

- add skip button navigate to profile page

skip button navigate to profile page

---

server/matching-algorithm/index.js
server/package.json
server/seeds/index.js

- move matching algo repo from root to server folder

move matching algo repo

---

client/package-lock.json
client/package.json
client/src/api/company.js
client/src/components/CompanyDropDown/Item.jsx
client/src/components/CompanyDropDown/index.jsx
client/src/index.css
client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx
client/src/pages/OpeningDashboardPage/GetAllOpenings.jsx
client/src/state/index.js
client/src/tailwind.js
client/tailwind.config.js
server/app.js
server/matching-algorithm/index.js
server/seeds/companies.js
server/src/controllers/Company.js
server/src/models/Company.js
server/src/routes/Company.js

- Created a dropdown component that show company name and search for company name
- client/src/api/company.js: api call from frontend
- client/src/components/CompanyDropDown/Item.jsx: frontend dropdown item component
- client/src/components/CompanyDropDown/index.jsx: dropdown component with api call to get companies and search
- client/src/index.css: add custom style for dropdown
- client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx: modify how create component change
- client/src/tailwind.js: source of tailwind config
- client/tailwind.config.js: import from source
- server/seeds/companies.js: script for import data from simplify api to mongodb
- server/src/controllers/Company.js: controller for company get endpoint
- server/src/models/Company.js: model for company …

Company dropdown with search

---

client/src/App.jsx
client/src/api/request.js
client/src/pages/RequestDashboardPage/CreateRequestModal.jsx
client/src/pages/RequestDashboardPage/RequestDashboard.jsx
client/src/state/index.js

- Make CreateRequest functional with modal frontend interface
- client/src/App.jsx
- client/src/api/request.js
- client/src/pages/RequestDashboardPage/CreateRequestModal.jsx
- client/src/pages/RequestDashboardPage/RequestDashboard.jsx
https://github.com/hoangr1010/Cupid/assets/140891599/c45fd548-e731-4aaf-a445-95b1c48aa715

Add modal to CreateRequest

---

client/src/api/request.js
client/src/pages/RequestDashboardPage/CreateRequest.jsx
client/src/pages/RequestDashboardPage/RequestDashboard.jsx
client/src/utils/request.js
server/src/controllers/Request.js
server/src/routes/Request.js

- add error handling
- client/src/pages/RequestDashboardPage/RequestDashboard.jsx
- 
https://github.com/hoangr1010/Cupid/assets/117782458/6f7c7ba1-b0f7-4484-940a-ae32d0c0738e

add error handling for change priority

---

client/src/api/opening.js
client/src/index.css
client/src/pages/OpeningDashboardPage/GetAllOpenings.jsx
client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
client/src/pages/OpeningDashboardPage/OpeningSlotCard.jsx
server/src/controllers/Opening.js
server/src/routes/Opening.js

- when opening is matched with request, it will ask referrer for approve or deny the matching. if approve -> both will turn to status "approved", deny -> both turn to "waiting" and delete field opening_id/request_id that is matched before
- client/src/api/opening.js: api call to backend for change status
- client/src/index.css: add class secondary-btn styling
- client/src/pages/OpeningDashboardPage/GetAllOpenings.jsx: transform to table view
- client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx: opening info modal and make action (approve/deny/refer)
- server/src/controllers/Opening.js: controllers in server for changing status in both referrer and candidate
Uploading Screen Recording 2024-05-11 at 12.07.49 PM.mov…

created pop up opening modal + updateOneOpeningField endpoint

---

client/src/api/opening.js
client/src/api/user.js
client/src/components/Sidebar/RouteContainer.jsx
client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx
client/src/pages/OpeningDashboardPage/VerificationBox.jsx
client/src/utils/gmail.js
client/src/utils/opening.js
server/package-lock.json
server/package.json
server/src/controllers/Opening.js
server/src/models/Passcode.js
server/src/routes/Opening.js
server/src/services/Sendgrid/sendEmail.js
server/src/utils/generatePasscode.js

- App will require company email verification when user create opening. It will send 30s-lifetime passcode when user create opening and ask user to input correct passcode to proceed creating opening
- client/src/api/opening.js: call processPasscode and verifyPasscode endpoint
- client/src/pages/OpeningDashboardPage/CreateOpeningModal.jsx: add gmail field and verification box that ask user to input passcode once it successfully sent to user gmail address.
- client/src/pages/OpeningDashboardPage/VerificationBox.jsx: the form that ask user to input 6-digit passcode
- client/src/utils/gmail.js: utils that verify valid gmail address and verify if the gmail address is belong to certain company
- client/src/utils/opening.js: utils that used for check if the form in creating opening valid
- …

Email verification

---

client/src/api/request.js
client/src/pages/RequestDashboardPage/CreateRequest.jsx
client/src/pages/RequestDashboardPage/RequestDashboard.jsx
server/src/models/Request.js

- Add job posting url when they create request
- client/src/api/request.js: add job posting url to create request
- client/src/pages/RequestDashboardPage/CreateRequest.jsx: modal to create request with job posting url
- client/src/pages/RequestDashboardPage/RequestDashboard.jsx: job posting direct
- server/src/models/Request.js: add job posting url in schema
- Any prove for testing? (image/video to prove)
https://github.com/hoangr1010/Cupid/assets/117782458/d15d0e44-03f2-4f67-a852-61b72cba8ee5

add job posting on create request

---

server/matching-algorithm/index.js
server/matching-algorithm/scale/scale.js
server/seeds/sampleData.js

- Calculate scale for each request when the algorithm running
- server/matching-algorithm/index.js: add scaleCalculate function
- server/matching-algorithm/scale/scale.js: scaleCalculate function that calculate scale for each request in the moment algorithm running
https://github.com/hoangr1010/Cupid/assets/117782458/4c31e366-9a2d-4ddc-a53f-8550c62c1254

calculate scale for each request

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/api/auth.js
client/src/state/index.js
client/src/utils/api.js
server/package-lock.json
server/package.json
server/src/controllers/Auth.js
server/src/middleware/Auth.js
server/src/routes/Opening.js
server/src/routes/Request.js
server/src/routes/User.js

- Create a new token whenever a user logs in then save it in redux
- Include the token in the header whenever a user sends a request
- Backend has to verify that token whenever receiving a request from frontend
- client/src/App.jsx
- client/src/api/auth.js
- client/src/state/index.js
- client/src/utils/api.js
- server/src/controllers/Auth.js
- server/src/middleware/Auth.js
- server/src/routes/Opening.js
- server/src/routes/Request.js
- server/src/routes/User.js

jwt authentication

---

client/src/pages/HomePage/StatisticsTable.jsx

- Fix statistics page loading indefinitely
- client/src/pages/HomePage/StatisticsTable.jsx
https://www.loom.com/share/5b1a50d526d84a2b867d4ed5d5ff64e1?sid=c3755bf5-718c-4105-95d7-7686bb8dd32f

Fix statistics page loading indefinitely

---

.github/workflows/server-deploy.yml
client/public/index.html
client/src/api/opening.js
client/src/components/Sidebar/SidebarItem.jsx
client/src/components/StatusBadge/index.jsx
client/src/index.css
client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
client/src/pages/OpeningDashboardPage/OpeningView.jsx
client/src/tailwind.js
server/src/controllers/Opening.js

- Polish Opening UI
- .github/workflows/server-deploy.yml: fix yml file
- client/public/index.html: change base text font
- client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx: change how it call redux to change status
- client/src/pages/OpeningDashboardPage/OpeningView.jsx: Change UI little bit
- xclient/src/tailwind.js: change grayLight color
- server/src/controllers/Opening.js: populate from opening to request to candidate of the opening

Polish sidebar opening

---

client/src/index.css
client/src/pages/HomePage/CompanyCard.jsx
client/src/pages/HomePage/StatisticsTable.jsx
client/src/pages/HomePage/index.jsx
client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
client/src/pages/RequestDashboardPage/RequestDashboard.jsx
client/src/tailwind.js

- Polish homepage UI to be better
- client/src/index.css: change filled-button to bold font
- client/src/pages/HomePage/CompanyCard.jsx: Card showing company statistic
- client/src/pages/HomePage/StatisticsTable.jsx: refactor to CompanyCard
- client/src/tailwind.js: add new color

polish homepage

---

server/package-lock.json
server/package.json
server/src/utils/extractPDF.js

- Created new repo with some change for pdf-parse package (I remove debug mode)
- server/package.json: leave my custom package instead of npm package
- every work fine

change package.json for parse-pdf

---

client/src/api/user.js
client/src/constant/auth.js
client/src/pages/ProfilePage/index.jsx
server/src/controllers/User.js
server/src/middleware/User.js
server/src/models/User.js
server/src/routes/User.js
server/src/utils/extractPDF.js
server/test/Opening/createOpening.js
server/test/Opening/getAllOpening.js
server/test/Request/createRequest.js
server/test/Request/getAllRequest.js
server/test/User/updateResume.js

- change resume schema to resume: {url, text}
- server/src/controllers/User.js: change how it save resume in user
- server/src/middleware/User.js: new middleware that parse pdf then save in resume.text
- server/src/models/User.js: new resume schema
- server/src/routes/User.js: add readResume middleware
- server/src/utils/extractPDF.js: create function parse resume by buffer
https://github.com/hoangr1010/Cupid/assets/117782458/f42f0478-1149-47ee-86e8-5faa44d9cc66

Change resume model

---

notification-service/.gitignore
notification-service/app.js
notification-service/index.js
notification-service/package-lock.json
notification-service/package.json
notification-service/utils/connectDB.js

- Initial set up for notification microservice
- Connect the microservice server with firestore
- Refer to design document for more information about the file serviceAccountKey.json
- notification-service/
[https://www.loom.com/share/0f9d5af798a24c02b28f2ff4a2b5d80f?sid=7e1586e1-1852-48fa-9471-704608ef08e7](url)

set up notification microservice server and connect firestore

---

server/matching-algorithm/index.js
server/matching-algorithm/scale/scale.js
server/seeds/index.js
server/seeds/sampleData.js
server/src/utils/connectRedis.js
server/test/MatchingAlgorithm/index.js
server/test/MatchingAlgorithm/runMatchingAlgorithm.js
server/test/index.test.js

- Upgraded matching algorithm so that everyone is given a chance to win a referral
- Made unit tests for matching algorithm
- Added job posting url to seed sample_data
- server/matching-algorithm/index.js
- server/matching-algorithm/scale/scale.js
- server/seeds/index.js
- server/test/MatchingAlgorithm/index.js
- server/test/MatchingAlgorithm/runMatchingAlgorithm.js
- server/test/index.test.js

Upgrade + Test algo

---

client/src/api/opening.js
client/src/components/NumberInput/index.jsx
client/src/pages/OpeningDashboardPage/CandidateView.jsx
client/src/pages/OpeningDashboardPage/CreateModal.jsx
client/src/pages/OpeningDashboardPage/OverviewView.jsx

- User can add up opening for existing opening
- client/src/components/NumberInput/index.jsx: Component input for component
- client/src/pages/OpeningDashboardPage/CandidateView.jsx: handle empty table
- client/src/pages/OpeningDashboardPage/CreateModal.jsx: Pop up that modify amoutn and create more opening
https://github.com/hoangr1010/Cupid/assets/117782458/211eb19d-d2c8-4436-9b8b-3a1057eb46f5

create opening for existing opening

---

notification-service/worker/deployed_lambda.mjs
notification-service/worker/old_handler.js
notification-service/worker/old_worker.js
notification-service/worker/package-lock.json
notification-service/worker/package.json

- Deploy worker to works with both AWS SES and Firestore database on AWS Lambda.
- notification-service/worker/deployed_lambda.mjs
- notification-service/worker/old_handler.js
- notification-service/worker/old_worker.js
- deployed_lambda.mjs should be named "index.mjs" before being deployed on aws lambda.
- You must also upload package.json and package-lock.json together with index.mjs for it to work.
- node_modules (if updated) should be updated to the additional lambda layer of worker.
https://github.com/hoangr1010/Cupid/assets/140891599/632771d8-a463-40e2-9c59-ab055f1d37f9

Deploy worker on aws lambda

---

client/src/api/opening.js
client/src/components/FileBox/index.jsx
client/src/components/PercentageChart/index.jsx
client/src/index.css
client/src/pages/OpeningDashboardPage/CandidateView/index.jsx
client/src/pages/OpeningDashboardPage/OpeningDashboard.jsx
client/src/pages/OpeningDashboardPage/OpeningInfoModal.jsx
client/src/pages/OpeningDashboardPage/OverviewView/CreateModal.jsx
client/src/pages/OpeningDashboardPage/OverviewView/index.jsx
client/src/pages/OpeningDashboardPage/StartingView/CreateOpeningModal.jsx
client/src/pages/OpeningDashboardPage/StartingView/VerificationBox.jsx
client/src/pages/OpeningDashboardPage/TableView/QuickAction.jsx
client/src/pages/OpeningDashboardPage/TableView/index.jsx
client/src/pages/RequestDashboardPage/RequestDashboard.jsx
client/src/state/index.js
client/src/utils/user.js
server/src/controllers/Opening.js
server/src/controllers/Request.js

- Referrer can approve, decline, accept, refer on request
- many huhu

make action on opening

---

notification-service/worker/deployed_lambda.mjs

- Update worker to push firestore doc to collection by recipientId.
- notification-service/worker/deployed_lambda.mjs

Update worker to work with recipientId as firestore collection

---

server/src/utils/notification.js

- add email field to Notification object
- server/src/utils/notification.js

add email field to Notification object

---

client/src/components/Notification/index.jsx
client/src/components/Notification/message.jsx
notification-service/microservice/Notification.js

- Notification UI
https://www.loom.com/share/001cbf52afce4a06b19d90da291bbc9a?t=4&sid=5ac9739f-51a7-499c-9f4f-b85e20a40ab7

Notification UI

---

client/src/pages/ProfilePage/AutoFill.jsx
client/src/pages/ProfilePage/ProfileView/Bio.jsx
client/src/pages/ProfilePage/ProfileView/Education.jsx
client/src/pages/ProfilePage/ProfileView/EducationCard.jsx
client/src/pages/ProfilePage/ProfileView/Experience.jsx
client/src/pages/ProfilePage/ProfileView/ExperienceCard.jsx
client/src/pages/ProfilePage/ProfileView/Portfolio.jsx
client/src/pages/ProfilePage/ProfileView/Project.jsx
client/src/pages/ProfilePage/ProfileView/ProjectCard.jsx
client/src/pages/ProfilePage/ProfileView/Resume.jsx
client/src/pages/ProfilePage/index.jsx

- Polished UI for profile page

finished basic UI for profile page

---

client/src/pages/RequestDashboardPage/RequestDashboard.jsx
server/seeds/sampleData.js

- Add "All" tab to request dashboard
- client/src/pages/RequestDashboardPage/RequestDashboard.jsx
- server/seeds/sampleData.js

Request frontend

---

client/src/components/FileBox/index.jsx
client/src/pages/RequestDashboardPage/RequestBox.jsx
client/src/pages/RequestDashboardPage/RequestCard.jsx
client/src/pages/RequestDashboardPage/RequestInfoModal.jsx

- Modal showing information of each request
https://www.loom.com/share/7420dc2598b3404e9b474813c53e0d5e?sid=29443cc8-c5c7-4c0b-8af2-ff3a8ab57ccc

Request Information card

---

client/src/pages/ProfilePage/ProfileView/Resume.jsx

- Added popup modal for resume uploading feature
- client/src/pages/ProfilePage/ProfileView/Resume.jsx

added popup modal for resume uploading feature

---

client/src/api/user.js
client/src/pages/ProfilePage/Forms/EducationForm.jsx
client/src/pages/ProfilePage/Forms/ExperienceForm.jsx
client/src/pages/ProfilePage/Forms/ProjectForm.jsx
client/src/pages/ProfilePage/ProfileView/Education.jsx
client/src/pages/ProfilePage/ProfileView/Experience.jsx
client/src/pages/ProfilePage/ProfileView/ExperienceCard.jsx
client/src/pages/ProfilePage/ProfileView/Project.jsx
client/src/pages/ProfilePage/index.jsx
client/src/state/index.js
client/src/utils/user.js
server/matching-algorithm/index.js

- polish add education/experience/project and make functionality work smoothly

Add form profile page

---

client/src/pages/ProfilePage/AutoFill/index.jsx
client/src/pages/ProfilePage/ProfileView/Resume.jsx
server/src/middleware/User.js

- Polished UI for Resume uploading and previewing
- client/src/pages/ProfilePage/AutoFill/index.jsx
- client/src/pages/ProfilePage/ProfileView/Resume.jsx
- server/src/middleware/User.js

Polished UI for Resume uploading and previewing

---

client/src/pages/HomePage/index.jsx

homepage UI

---

notification-service/worker/deployed_lambda.mjs
server/matching-algorithm/index.js

- Polish notification lambda in AWS.
- Update notiTypes used in algorithm.
- notification-service/worker/deployed_lambda.mjs
- server/matching-algorithm/index.js

Polish notification feature

---

client/src/pages/HomePage/StatisticsTable.jsx
client/src/pages/HomePage/index.jsx
client/src/utils/notiNavigate.js

search bar functional
